"""
Session-scoped conversation memory: for each session_id, keeps the last
few offers/FAQs that were actually SHOWN to the user (retrieved and used
in a real answer -- not every candidate that was merely scored), most
recent first.

Why this exists instead of just leaning on `history` text: RagEngine
already threads chat history through to the LLM, but that only helps once
an answer is generated by the LLM directly -- most answers here are
template-built "direct answer" shortcuts that never touch the LLM at all,
and even when the LLM is involved, a 1.5-3B local model with a small
context window (see config.OLLAMA_NUM_CTX) is not a reliable place to
store "which exact offer were we just talking about". This module keeps
that as structured data instead, so a follow-up like "how much was it
before the discount" can resolve back to the exact offer deterministically,
rather than hoping the model infers it from a wall of chat text.

Deliberately NOT persisted anywhere -- pure in-memory, per-process. Fine
for a single-worker local/dev deployment. If this ever needs to survive
restarts or run behind multiple workers, swap the dict in MemoryStore for
a Redis/sqlite-backed equivalent behind the same get() interface; nothing
above this module needs to change.
"""
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Optional

MAX_OFFERS_PER_SESSION = 4      # "remember the last 3 or 4 offers"
SESSION_TTL_SECONDS = 60 * 60   # evict a session after an hour of inactivity


@dataclass
class RememberedOffer:
    """A trimmed, stable snapshot of one offer/FAQ's metadata at the moment
    it was shown to the user. Deliberately a copy, not a live reference into
    RagEngine.docs -- stays correct even if the index gets reloaded/rebuilt
    later in the process's life, and keeps this module decoupled from
    RagEngine's internal doc representation."""
    id: str                 # "offer:1234" / "faq:56" -- source:id, globally unique
    source: str              # "offer" | "faq"
    merchant: Optional[str]
    title: Optional[str]
    metadata: dict            # full metadata dict, as-is, for downstream use
    shown_at: float = field(default_factory=time.time)


class SessionMemory:
    """Ring buffer of the last MAX_OFFERS_PER_SESSION offers/FAQs shown in
    one conversation, most-recent-first. One instance per session_id."""

    def __init__(self):
        self._offers: deque = deque(maxlen=MAX_OFFERS_PER_SESSION)
        self.last_active = time.time()
        self._lock = threading.Lock()

    def remember(self, docs: list):
        """docs: list of retrieved-doc dicts in RagEngine's shape, i.e. each
        one has a "metadata" key (this is exactly the shape of
        result["sources"] from RagEngine.answer()). Only offer/FAQ entries
        are kept; anything else is ignored. Callers should pass what was
        actually shown/used in the answer (e.g. raw_sources[:3]), not the
        full internal candidate pool, so memory reflects what the user
        actually saw, not everything the retriever merely considered."""
        with self._lock:
            self.last_active = time.time()
            # Iterate in reverse: each appendleft puts its item at the
            # front, so processing docs back-to-front means docs[0] (the
            # highest-relevance source of THIS turn) is appendleft'd last
            # and ends up frontmost -- i.e. "most relevant this turn" beats
            # "2nd most relevant this turn", and this turn's items end up
            # ahead of any earlier turn's, giving an overall order of
            # most-recent-turn-first, most-relevant-within-turn-first.
            for doc in reversed(docs):
                meta = doc.get("metadata", {}) or {}
                source = meta.get("source")
                if source not in ("offer", "faq"):
                    continue
                offer_id = f"{source}:{meta.get('id')}"
                # De-dupe: if this exact item is already cached, drop the old
                # copy so re-appending it moves it to the front (most-recent)
                # instead of creating a duplicate entry.
                if any(o.id == offer_id for o in self._offers):
                    self._offers = deque(
                        (o for o in self._offers if o.id != offer_id),
                        maxlen=MAX_OFFERS_PER_SESSION,
                    )
                self._offers.appendleft(RememberedOffer(
                    id=offer_id,
                    source=source,
                    merchant=meta.get("merchant"),
                    title=meta.get("title") or meta.get("question"),
                    metadata=meta,
                ))

    def recent(self, n: int = None) -> list:
        """Returns the last-shown offers/FAQs, most-recent-first, in the
        same {"metadata": {...}} shape RagEngine's retrieved docs use --
        so callers can pass this straight into RagEngine.answer(recent_offers=...)
        without any reshaping."""
        with self._lock:
            items = list(self._offers)
        items = items[:n] if n else items
        return [{"metadata": o.metadata} for o in items]


class MemoryStore:
    """Process-wide session_id -> SessionMemory map, with lazy eviction of
    stale sessions so a long-running server doesn't leak memory across
    thousands of abandoned chat tabs."""

    def __init__(self):
        self._sessions: dict = {}
        self._lock = threading.Lock()

    def get(self, session_id: str) -> SessionMemory:
        with self._lock:
            self._evict_stale()
            if session_id not in self._sessions:
                self._sessions[session_id] = SessionMemory()
            return self._sessions[session_id]

    def _evict_stale(self):
        cutoff = time.time() - SESSION_TTL_SECONDS
        stale = [sid for sid, sess in self._sessions.items() if sess.last_active < cutoff]
        for sid in stale:
            del self._sessions[sid]
