"""
Session-scoped conversation memory: for each session_id, keeps the last
few offers/FAQs that were actually SHOWN to the user (retrieved and used
in a real answer -- not every candidate that was merely scored), most
recent first.

Why this exists instead of just leaning on `history` text: RagEngine
already threads chat history through to the LLM, but that only helps once
an answer is generated by the LLM directly -- most answers here are
template-built "direct answer" shortcuts that never touch the LLM at all,
and even when the LLM is involved, a 1.5-3B local model with a small
context window (see config.OLLAMA_NUM_CTX) is not a reliable place to
store "which exact offer were we just talking about". This module keeps
that as structured data instead, so a follow-up like "how much was it
before the discount" can resolve back to the exact offer deterministically,
rather than hoping the model infers it from a wall of chat text.

CHANGED: was a process-local dict (fine for a single-worker dev deploy, but
explicitly NOT safe the moment you run more than one uvicorn worker/replica
-- each worker would keep its own inconsistent memory of what a session was
shown, so follow-ups would randomly work depending on which worker handled
which request; see git history for the original in-process version). Now
backed by Redis, so memory is shared across workers/replicas and survives
app restarts/redeploys.

Public interface is unchanged on purpose: MemoryStore().get(session_id)
still returns an object with .remember(docs) / .recent(n) -- app.py doesn't
need to change at all.
"""
import json
import time
from typing import Optional

import redis

import config

MAX_OFFERS_PER_SESSION = 4      # "remember the last 3 or 4 offers"
SESSION_TTL_SECONDS = 60 * 60   # evict a session after an hour of inactivity


def _key(session_id: str) -> str:
    return f"waffarha:session:{session_id}:offers"


class SessionMemory:
    """Thin, stateless-in-Python wrapper bound to one session_id -- all
    actual data lives in Redis under _key(session_id). Cheap to construct
    per-request; there's nothing here to leak or need eviction for, unlike
    the old per-session Python object (Redis's own key TTL, refreshed on
    every write, replaces the old manual eviction loop)."""

    def __init__(self, client: "redis.Redis", session_id: str):
        self._r = client
        self._key = _key(session_id)

    def remember(self, docs: list):
        """docs: list of retrieved-doc dicts in RagEngine's shape, i.e. each
        one has a "metadata" key (this is exactly the shape of
        result["sources"] from RagEngine.answer()). Only offer/FAQ entries
        are kept; anything else is ignored. Callers should pass what was
        actually shown/used in the answer (e.g. raw_sources[:3]), not the
        full internal candidate pool, so memory reflects what the user
        actually saw, not everything the retriever merely considered.

        Stored as a Redis list of JSON strings, most-recent-first, capped
        at MAX_OFFERS_PER_SESSION. De-dupe + reorder happens in Python
        (read-modify-write) rather than server-side Redis list ops, since
        "drop this id wherever it appears, then reinsert at the front" has
        no single atomic Redis command -- the whole read+rewrite is wrapped
        in a pipeline so the key is never left half-updated, but note this
        means two concurrent remember() calls for the *same* session_id
        (e.g. a user double-submitting) could race; acceptable here since
        the worst case is one of the two updates winning outright, not
        corrupted data, and a single browser tab doesn't send concurrent
        chat requests for the same session in practice.
        """
        items = []
        for doc in docs:
            meta = doc.get("metadata", {}) or {}
            source = meta.get("source")
            if source not in ("offer", "faq"):
                continue
            items.append({
                "id": f"{source}:{meta.get('id')}",
                "metadata": meta,
                "shown_at": time.time(),
            })
        if not items:
            return

        existing_raw = self._r.lrange(self._key, 0, -1)
        existing = []
        for x in existing_raw:
            try:
                existing.append(json.loads(x))
            except (json.JSONDecodeError, TypeError):
                continue
        new_ids = {it["id"] for it in items}
        # Drop any existing entries that duplicate an id in this turn, so
        # re-showing an offer moves it to the front instead of creating a
        # duplicate -- same de-dupe behavior as the original deque version.
        existing = [e for e in existing if e.get("id") not in new_ids]
        # `items` is already highest-relevance-first for this turn (callers
        # pass raw_sources[:3] in that order); prepending it ahead of
        # `existing` gives the same "most-recent-turn-first,
        # most-relevant-within-turn-first" ordering the original
        # reversed()+appendleft trick produced.
        merged = (items + existing)[:MAX_OFFERS_PER_SESSION]

        pipe = self._r.pipeline()
        pipe.delete(self._key)
        pipe.rpush(self._key, *[json.dumps(m) for m in merged])
        pipe.expire(self._key, SESSION_TTL_SECONDS)
        pipe.execute()

    def recent(self, n: int = None) -> list:
        """Returns the last-shown offers/FAQs, most-recent-first, in the
        same {"metadata": {...}} shape RagEngine's retrieved docs use --
        so callers can pass this straight into RagEngine.answer(recent_offers=...)
        without any reshaping."""
        stop = (n - 1) if n else -1
        raw = self._r.lrange(self._key, 0, stop)
        out = []
        for x in raw:
            try:
                parsed = json.loads(x)
                if isinstance(parsed, dict) and "metadata" in parsed:
                    out.append({"metadata": parsed["metadata"]})
            except (json.JSONDecodeError, TypeError):
                continue
        return out


class MemoryStore:
    """Process-wide handle to a single Redis connection pool. get() is
    cheap (just wraps the shared client + a session_id), so there's no
    session_id -> object map to maintain in Python anymore -- Redis is the
    only place session state actually lives."""

    def __init__(self, redis_url: Optional[str] = None):
        self._r = redis.from_url(redis_url or config.REDIS_URL, decode_responses=True)
        # Fail fast if Redis isn't reachable, same spirit as RagEngine's
        # Ollama check in rag_engine.py -- a clear error at startup beats a
        # mysterious failure on the first chat request.
        self._r.ping()

    def get(self, session_id: str) -> SessionMemory:
        return SessionMemory(self._r, session_id)
